### ISSUE TITLE
KernelSu modules doesn't work

### ISSUE THREAD

**Issue by DiamivaeBro** [QKIvan/android_kernel_google_redbull#1]
KernelSu modules doesn't work
It looks like:
![Screenshot_20231211-005003](https://github.com/QKIvan/android_kernel_google_redbull/assets/119186976/ca0b5d05-f832-4c94-8540-8ff450088b17)
Logs:
[KernelSU_bugreport_2023-12-11_01_18.tar.gz](https://github.com/QKIvan/android_kernel_google_redbull/files/13629459/KernelSU_bugreport_2023-12-11_01_18.tar.gz)

**Comment by rahezo** [comment]
Can i get your kenel su boot image? or whole package

**Comment by DiamivaeBro** [comment]
> Can i get your kenel su boot image? or whole package

You can find it in tags

**Comment by tomnguyenhieu** [comment]
> > Can i get your kenel su boot image? or whole package
> 
> You can find it in tags

Hi can u check my issues (in issues tag) ?? Im quiet new here XD

**Comment by QKIvan** [comment]
It should be fixed in the next release.
Maybe it'll be released tomorrow.

**Comment by QKIvan** [comment]
I probably don't have time to deal with that.
Reopen this issue until it is fixed.

**Comment by Myviforme** [comment]
https://github.com/F-19-F/android_kernel_oneplus_msm8998/commit/1042d5601a1c0db08c9a9cea89d1895e74576a27
repair this

**Comment by QKIvan** [comment]
> [F-19-F/android_kernel_oneplus_msm8998@1042d56](https://github.com/F-19-F/android_kernel_oneplus_msm8998/commit/1042d5601a1c0db08c9a9cea89d1895e74576a27) repair this

This issue was fixed before this. I just didn't have the time to adapt Stock separately again, so I didn't close the issue.

**Comment by QKIvan** [comment]
I think it's necessary for me to close this issue (since it's been fixed), after which I'll commit the available ksu commit to another branch for others to build on their own.
