### ISSUE TITLE
Error boot prepare

### ISSUE THREAD

**Issue by tomnguyenhieu** [QKIvan/android_kernel_google_redbull#2]
Currently I am on the rom pixel experience plus edition A13 (September 26, 2023) and these are the steps I did
- fastboot flash vbmeta vbmeta.img (I got the vbmeta in the pixel experience plus edition rom I'm using)
- fastboot flash boot boot.img
- fastboot flash boot dtbo.img
- fastboot flash vendor_boot vendor_boot.img
And after all those steps, my phone stuck in fastboot and said "Error boot prepare". So what is the problem I have here? I checked my kernel version is 4.19.269, different from yours. Is that a problem?
And one more thing is that the nekko kernel 0.1 version is different from the version with KernelSU extension?

**Comment by QKIvan** [comment]
I merged ack,so different kernel versions are not the problem.
As well, did you run fastboot -w after closing vbmeta? I think you need to run this command to make your device booted (this will cerase your userdata).(btw I tested my kernel in CalyxOS14 and ProtonAOSP 12.1 and I continue it can boot and worked well.In my tests, only GrapheneOS is completely can’t booy (idk why), and I didn't test with PixelExperience.

You can see two zips in the prerelease, one with KernelSU and the other without, that's all the difference, they both belong to Nekko-0.1.

**Comment by QKIvan** [comment]
For health reasons, I still don't have a fix for the KernelSU module not working. and 13 branch is still wip, if you want to fix it by yourself, please reset the commit to Nekko 1.1 release.

**Comment by tomnguyenhieu** [comment]
I just followed the steps I listed above, there is no fastboot -w step and I don't fully understand what vbmeta is and how it affects whether the device boots up or not.  Anyway, the data on this device is very important and I'm too lazy to back it up, so if I have to delete all the data, I probably won't use kernelsu anymore.  
At the same time, because I'm new to kernelsu, I'm curious to play around with it to see if it's any different from magisk. I have almost no knowledge about building kernels or similar things.  
If you don't mind, could you provide a more detailed tutorial on commands related to vbmeta and also flashing kernelsu?  Sorry if I'm too demanding 🤣
